Discarded courses
LedgerProject/eschooltul_backend pull request #20
Opened 2021-04-20 09:36 UTC by AlejandroAdrian

Signed-off-by: Alejandro <alejandro.adrian@exponentiateam.com>

2021-04-20 14:58 UTC, mapreal19 requested changes

2021-04-20 14:58 UTC, mapreal19 commented on app/models/course.rb
> +  include Discard::Model
follow this order: https://github.com/rubocop/rails-style-guide#macro-style-methods

2021-04-20 14:58 UTC, mapreal19 commented on app/models/course.rb
> +  include Discard::Model
the include at the top and then the default scope

2021-04-20 14:58 UTC, mapreal19 commented on app/views/courses/_courses_table.html.erb
>      <% @courses.each do |c| %>
rename the variable `c`  with `course`

2021-04-20 14:58 UTC, mapreal19 commented on app/views/courses/_courses_table.html.erb
> +      <% if c.discarded_at.nil? %>
You're using the default scope `kept`, Is this really necessary?

2021-04-20 14:58 UTC, mapreal19 commented on app/views/courses/index.html.erb
> +        url: discard_courses_path,
fix the indentation here

2021-04-20 14:58 UTC, mapreal19 commented on app/views/discard_courses/_courses_table.html.erb
> +    <div class="flex">
use 2 spaces for indentation

2021-04-20 14:58 UTC, mapreal19 commented on app/views/discard_courses/_courses_table.html.erb
> +      <% unless c.discarded_at.nil? %>
`if course.discarded?` better?

2021-04-20 14:58 UTC, mapreal19 commented on app/views/grades/courses/_courses_table.html.erb
> +      <% if c.discarded_at.nil? %>
is it needed?

2021-04-20 14:58 UTC, mapreal19 commented on spec/requests/discard_courses_request_spec.rb
> +  describe "courses#discard" do
`POST /discard` use this describe

2021-04-20 14:58 UTC, mapreal19 commented on spec/requests/discard_courses_request_spec.rb
> +      expect(flash[:notice]).to eq("Course was successfully discarded")
you can check also the object `expect(course.reload.discarded?).to be(true)`

2021-04-20 14:58 UTC, mapreal19 commented on spec/requests/discard_courses_request_spec.rb
> +    it "course is discarded" do
explain what it does: `discards course`

2021-04-20 14:58 UTC, mapreal19 commented on spec/requests/discard_courses_request_spec.rb
> +      course = create(
create a trait `discarded` for this case. https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#defining-traits

2021-04-20 15:26 UTC, AlejandroAdrian commented on app/models/course.rb
> +  include Discard::Model
Done

2021-04-20 15:26 UTC, AlejandroAdrian commented on app/views/courses/_courses_table.html.erb
>      <% @courses.each do |c| %>
Done

2021-04-20 15:27 UTC, AlejandroAdrian commented on app/views/courses/_courses_table.html.erb
> +      <% if c.discarded_at.nil? %>
It's not needed. I removed it. Done

2021-04-20 15:27 UTC, AlejandroAdrian commented on app/views/courses/index.html.erb
> +        url: discard_courses_path,
Done

2021-04-20 15:27 UTC, AlejandroAdrian commented on app/views/discard_courses/_courses_table.html.erb
> +    <div class="flex">
Done

2021-04-20 15:28 UTC, AlejandroAdrian commented on app/views/discard_courses/_courses_table.html.erb
> +      <% unless c.discarded_at.nil? %>
The unless statement is not needed using the default scope. I removed the statement

2021-04-20 15:35 UTC, AlejandroAdrian commented on spec/requests/discard_courses_request_spec.rb
> +  describe "courses#discard" do
Done

2021-04-20 15:37 UTC, AlejandroAdrian commented on spec/requests/discard_courses_request_spec.rb
> +      expect(flash[:notice]).to eq("Course was successfully discarded")
Line 12 is needed to be removed using the line you suggest?

2021-04-20 15:37 UTC, AlejandroAdrian commented on spec/requests/discard_courses_request_spec.rb
> +    it "course is discarded" do
Done

2021-04-20 16:02 UTC, AlejandroAdrian commented on spec/requests/discard_courses_request_spec.rb
> +      course = create(
Done

2021-04-21 08:45 UTC, mapreal19 commented on spec/requests/discard_courses_request_spec.rb
> +      expect(flash[:notice]).to eq("Course was successfully discarded")
No, just add a new expectation (after line 13)

2021-04-21 08:48 UTC, mapreal19 commented on app/views/discard_courses/_courses_table.html.erb
> +    <% unless c.discarded_at.nil? %>
`if course.discarded?`

We have these methods:
![image](https://user-images.githubusercontent.com/3055997/115525070-0d2ce080-a28f-11eb-8a32-4298c3c47e4c.png)

2021-04-21 08:54 UTC, AlejandroAdrian commented on spec/requests/discard_courses_request_spec.rb
> +      expect(flash[:notice]).to eq("Course was successfully discarded")
Ah OK. Done

2021-04-21 09:01 UTC, AlejandroAdrian commented on app/views/discard_courses/_courses_table.html.erb
> +    <% unless c.discarded_at.nil? %>
I know, but the unless statement is not needed anymore as the model course has the default_scope and in the discard_courses_controller we make the filter with .with_discarded.discarded. I remove the statement. Maybe instead of @course is it better to rename the variable with another name: @discarded_courses?

2021-04-21 15:35 UTC, mapreal19 approved these changes

2021-04-21 15:35 UTC, mapreal19 commented on app/views/discard_courses/_courses_table.html.erb
> +    <% unless c.discarded_at.nil? %>
Fine for now 👍

2021-04-21 15:35 UTC, merged