Joaquin/feat/associate and certificate
LedgerProject/eschooltul_backend pull request #23
Opened 2021-05-06 08:41 UTC by JKinnez

2021-05-06 14:46 UTC, mapreal19 requested changes

2021-05-06 14:46 UTC, mapreal19 commented on app/views/students/_form.html.erb
> +    <% @student.documents.each do |d| %>
don't use `d` for naming the variable. Use `document` instead.

2021-05-06 14:46 UTC, mapreal19 commented on config/environments/development.rb
> +  config.active_storage.replace_on_assign_to_many = false
If this is the same for the 3 environments put this config in the application.rb file

2021-05-07 08:25 UTC, JKinnez commented on app/views/students/_form.html.erb
> +    <% @student.documents.each do |d| %>
Done

2021-05-07 08:25 UTC, JKinnez commented on config/environments/development.rb
> +  config.active_storage.replace_on_assign_to_many = false
Done

2021-05-07 08:41 UTC, mapreal19 approved these changes

2021-05-07 09:05 UTC, merged