Generate Student EDA
LedgerProject/eschooltul_backend pull request #38
Opened 2021-06-09 09:30 UTC by AlejandroAdrian

Signed-off-by: Alejandro <alejandro.adrian@exponentiateam.com>

2021-06-10 09:13 UTC, mapreal19 requested changes

2021-06-10 09:13 UTC, mapreal19 commented on app/views/students/_student.html.erb
> +    <p class="text-sm text-gray-500 capitalize"><%= t("student.yearsold", student_age: Date.today.year-student.birthday.year) %></p>
extract a method for the student to calculate its age.

2021-06-10 09:13 UTC, mapreal19 commented on config/locales/models/student_edas/en.yml
> +      percert: "Percent"
percent?

2021-06-10 09:13 UTC, mapreal19 commented on config/locales/models/student_edas/es.yml
> +      percert: "Nota"
percent?

2021-06-10 09:13 UTC, mapreal19 commented on config/locales/views/student_eda/es.yml
> +    generate: "Generar Expediente Digial del Estudiante"
typo digial

2021-06-10 09:13 UTC, mapreal19 commented on db/seeds.rb
> +          birthday: DateTime.new(2011, 1, 1)
you can do `10.years.from_now` too since they don't age ;)

2021-06-10 09:13 UTC, mapreal19 commented on spec/requests/student_edas_request_spec.rb
> +    it "creates student EDA", :vcr do
vcr is needed?

2021-06-10 09:13 UTC, mapreal19 commented on spec/requests/student_edas_request_spec.rb
> +      end.to change(StudentEda, :count).by(1)
don't need to test this change if you're testing the eda is present below

2021-06-10 10:00 UTC, AlejandroAdrian commented on .rubocop.yml
> +  Enabled: False
I removed it

2021-06-10 10:00 UTC, AlejandroAdrian commented on app/controllers/student_edas_controller.rb
> +    params.require(:student_eda).permit(:student_code, :mode_of_study, :mode_of_delivery, :language,
Done

2021-06-10 10:01 UTC, AlejandroAdrian commented on app/models/student_eda.rb
> +  validate :student_code
its presence is supposed to be validated, I forgot it.

2021-06-10 10:01 UTC, AlejandroAdrian commented on app/views/students/_student.html.erb
> +    <p class="text-sm text-gray-500 capitalize"><%= t("student.yearsold", student_age: Date.today.year-student.birthday.year) %></p>
Done

2021-06-10 10:02 UTC, AlejandroAdrian commented on config/locales/models/student_edas/en.yml
> +      percert: "Percent"
This is what it says in the standard

2021-06-10 10:03 UTC, AlejandroAdrian commented on config/locales/models/student_edas/es.yml
> +      percert: "Nota"
This is what it says in the standard. I assume it is the mark, but we have no more information

2021-06-10 10:03 UTC, AlejandroAdrian commented on config/locales/views/student_eda/es.yml
> +    generate: "Generar Expediente Digial del Estudiante"
Done

2021-06-10 10:03 UTC, AlejandroAdrian commented on db/seeds.rb
> +          birthday: DateTime.new(2011, 1, 1)
Done

2021-06-10 10:03 UTC, AlejandroAdrian commented on spec/requests/student_edas_request_spec.rb
> +      end.to change(StudentEda, :count).by(1)
Done

2021-06-10 10:04 UTC, AlejandroAdrian commented on spec/requests/student_edas_request_spec.rb
> +    it "creates student EDA", :vcr do
I assumed that a xml file is created with it, but not

2021-06-11 06:29 UTC, mapreal19 commented on app/models/student.rb
> +  def self.calculate_age(student)
it should be an instance method

```
def age # call it with student.age
  Time.zone.today - birthday.year
end
```

2021-06-11 06:30 UTC, mapreal19 commented on spec/requests/student_edas_request_spec.rb
> +    it "creates student EDA", :vcr do
vcr is used when interacting with some API outside of our control

2021-06-11 07:25 UTC, AlejandroAdrian commented on app/models/student.rb
> +  def self.calculate_age(student)
Done

2021-06-11 07:25 UTC, AlejandroAdrian commented on spec/requests/student_edas_request_spec.rb
> +    it "creates student EDA", :vcr do
OK, I understand it now

2021-06-11 08:39 UTC, mapreal19 approved these changes

2021-06-11 14:41 UTC, merged